### ISSUE TITLE
Exception during weaving on project that does not use Name.Of

### ISSUE THREAD

**Issue by MovGP0** [NickStrupat/NameOf#6]
I have another exception when building a project that includes the NameOf.Fody library, but does not use it: 

    Error	873	Fody: An unhandled exception occurred:
    Exception:
    Sequence contains no matching element
    StackTrace:
       at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
       at NameOf.Fody.ModuleWeaver.Execute() in c:\Development\NameOf\NameOf.Fody\ModuleWeaver.cs:line 28
       at lambda_method(Closure , Object )
       at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 135
       at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 53
    Source:
    System.Core
    TargetSite:
    TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
        CN

**Comment by NickStrupat** [comment]
Good catch! I've fixed that in NuGet package 0.8.3.
